name: Docker Image CI

on:
  push:
    branches: [ "main", "dockerfile" ]
  pull_request:
    branches: [ "main", "dockerfile"]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./ytt-executor --file ./ytt-executor/Dockerfile --tag ytt-executor:$(date +%s)
